import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const familyhistory = [
  {
    number: "1",
    name: "Jhoanna Mae Dela Cruz",
    relationship: "Mother",
    condition: "Hypertension",
    procedure: "N/A",
  },
  {
    number: "2",
    name: "Jhomar Dela Cruz",
    relationship: "Father",
    condition: "Cardiomyopathy",
    procedure: "Angioplasty",
  },
];
export default function FamilySocialHistoryPDF() {
  return (
    <>
      <div className="text-black text-center text-base font-bold leading-5 mt-8 max-md:ml-1 max-md:mt-10">
        JUAN DELA CRUZ
      </div>
      <div className="text-black text-center text-base text-xs leading-5 mb-1 max-md:ml-1 max-md:mt-10 mb-10">
        Family/ Social History
      </div>
      <Table>
        <TableCaption>
          Generated by John Doe through EndoTracker on April 30, 2024
        </TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[200px]">No.</TableHead>
            <TableHead>Name</TableHead>
            <TableHead>Relationship</TableHead>
            <TableHead>Condition</TableHead>
            <TableHead>Procedure</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody className="bg-white">
          {familyhistory.map((familyhistory) => (
            <TableRow key={familyhistory.name}>
              <TableCell className="font-medium">
                {familyhistory.number}
              </TableCell>
              <TableCell>{familyhistory.name}</TableCell>
              <TableCell>{familyhistory.relationship}</TableCell>
              <TableCell>{familyhistory.condition}</TableCell>
              <TableCell>{familyhistory.procedure}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </>
  );
}
