import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const masterdata = [
  {
    name: "Juan Dela Cruz",
    age: "74",
    birthday: "January 01, 1950",
    gender: "Male",
    address: "1 Pasay Rd. Pasay City, Metro Manila",
    contact: "0999 999 9999",
    stroke: "Yes",
    allergies: "Pennicilin | Effect: Headache",
    attendingDoctor: "Dr. Maria Johnson",
  },
];
export default function MasterDataPDF() {
  return (
    <>
      <div className="text-black text-center text-base font-bold leading-5 mt-8 max-md:ml-1 max-md:mt-10">
        JUAN DELA CRUZ
      </div>
      <div className="text-black text-center text-base text-xs leading-5 mb-1 max-md:ml-1 max-md:mt-10 mb-10">
        Master Data
      </div>
      <Table>
        <TableCaption>
          Generated by John Doe through EndoTracker on April 30, 2024
        </TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[200px]">Name</TableHead>
            <TableHead>Age</TableHead>
            <TableHead>Birthday</TableHead>
            <TableHead>Gender</TableHead>
            <TableHead>Address</TableHead>
            <TableHead>Contact</TableHead>
            <TableHead>Stroke</TableHead>
            <TableHead>Allergies</TableHead>
            <TableHead>Attending Doctor</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody className="bg-white">
          {masterdata.map((masterdata) => (
            <TableRow key={masterdata.name}>
              <TableCell className="font-medium">{masterdata.name}</TableCell>
              <TableCell>{masterdata.age}</TableCell>
              <TableCell>{masterdata.birthday}</TableCell>
              <TableCell>{masterdata.gender}</TableCell>
              <TableCell>{masterdata.address}</TableCell>
              <TableCell>{masterdata.contact}</TableCell>
              <TableCell>{masterdata.stroke}</TableCell>
              <TableCell>{masterdata.allergies}</TableCell>
              <TableCell>{masterdata.attendingDoctor}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </>
  );
}
