import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

const medicalhistory = [
  {
    number: "1",
    diagnosis: "Type 2 Diabetes",
    date: "2020-01-24",
    provider: "Dr. Harold Chiu",
    hospital: "Philippine General Hospital",
  },
  {
    number: "2",
    diagnosis: "Ketoacidosis",
    date: "2023-08-09",
    provider: "Dr. Eli Cruz",
    hospital: "Taytay Hospital",
  },
];
export default function MedicalHistoryPDF() {
  return (
    <>
      <div className="text-black text-center text-base font-bold leading-5 mt-8 max-md:ml-1 max-md:mt-10">
        JUAN DELA CRUZ
      </div>
      <div className="text-black text-center text-base text-xs leading-5 mb-1 max-md:ml-1 max-md:mt-10 mb-10">
        Medical History
      </div>
      <Table>
        <TableCaption>
          Generated by John Doe through EndoTracker on April 30, 2024
        </TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[200px]">No.</TableHead>
            <TableHead>No.</TableHead>
            <TableHead>Diagnosis</TableHead>
            <TableHead>Date</TableHead>
            <TableHead>Provider</TableHead>
            <TableHead>Hospital</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody className="bg-white">
          {medicalhistory.map((medicalhistory) => (
            <TableRow key={medicalhistory.number}>
              <TableCell className="font-medium">
                {medicalhistory.diagnosis}
              </TableCell>
              <TableCell>{medicalhistory.date}</TableCell>
              <TableCell>{medicalhistory.provider}</TableCell>
              <TableCell>{medicalhistory.hospital}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </>
  );
}
