"use client";
import * as React from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Link } from "next/link"; // Import Link component
import { currentUser } from "@/app/store";
import { toast } from "react-toastify";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useReportsNav } from "../../store";
import ReportsNav from "./reportsNav";
import TotalVisits from "./components/totalvisits";
import NewAndReturning from "./components/newandreturning";

export default function ClinicVisitsVolume() {
  const { selected } = useReportsNav();
  const router = useRouter(); // Initialize useRouter

  const patientInfo = [
    {
      name: "Marvin Raymundo",
      age: "25",
      diagnosis: "Type 2 Diabetes with Ketoacidosis",
      date: "April 20, 2024",
    },
    {
      name: "Ahmed Ali",
      age: "25",
      diagnosis: "Type 1 Diabetes Mellitus with Hypoglycemia",
      date: "April 19, 2024",
    },
    {
      name: "Elena Rodriguez",
      age: "24",
      diagnosis: "Type 2 Diabetes Mellitus with Neuropathy",
      date: "April 10, 2024",
    },
    {
      name: "Amir Khan",
      age: "45",
      diagnosis: "Type 1 Diabetes Mellitus with Retinopathy",
      date: "January 28, 2024",
    },
  ];

  return (
    <div className="bg-white h-screen flex">
      <div className="flex flex-col grow shrink-0 self-start px-8 mt-14 basis-0 leading-[150%] w-fit max-md:mt-10 max-md:max-w-full">
        <div className="text-xl font-semibold text-black max-md:max-w-full">
          Reports
        </div>
        <div className="shrink-0 mt-5 h-px bg-black border border-black border-solid max-md:max-w-full" />
        <div className="flex justify-between gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-8 text-base font-semibold text-black max-md:max-w-full">
            CLINIC VISITS VOLUME
          </div>

          <div className="mt-8 text-xs text-blue-500 max-md:max-w-full">
            <button>Download (.pdf)</button>
          </div>
        </div>
        <div className="flex justify-between items-center gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-4 ml-4 text-sm font-semibold text-black max-md:max-w-full">
            Date Generated: 2024-04-06
            <br />
            Generated by: Dr. John Doe
          </div>

          <button className="flex gap-1 text-sm py-1 px-2 whitespace-nowrap rounded-md border border-black border-solid">
            <Image
              loading="lazy"
              height={0}
              width={0}
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/80c3069d4b41f9638143beaab01442a1ee1faa03e69b5f02684db5e14364bb41?"
              className="aspect-square object-contain object-center w-4 overflow-hidden shrink-0 max-w-full"
            />
            <div>FILTER</div>
          </button>
        </div>
        <div className="mt-5 ml-8 mr-8">
          <ReportsNav />
          {selected === "Total Visits Over Time" ? (
            <TotalVisits />
          ) : selected === "New vs. Returning Patients" ? (
            <>
              <NewAndReturning />
            </>
          ) : (
            ""
          )}
        </div>
      </div>
    </div>
  );
}
