"use client";
import * as React from "react";

import { currentUser } from "@/app/store";

import {
	Table,
	TableBody,
	TableCaption,
	TableCell,
	TableFooter,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";

export function FollowUpListPDF({ patientInfo }) {
	return (
		<div className="bg-white h-screen flex" style={{ overflowY: "scroll", maxHeight: "100vh" }}>
			<div className="flex flex-col grow shrink-0 self-start px-8 mt-14 basis-0 leading-[150%] w-fit max-md:mt-10 max-md:max-w-full">
				<div className="text-xl font-semibold text-black max-md:max-w-full">Reports</div>
				<div className="shrink-0 mt-5 h-px bg-black border border-black border-solid max-md:max-w-full" />
				<div className="flex justify-between gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
					<div className="mt-8 text-base font-semibold text-black max-md:max-w-full">
						LATE FOR FOLLOW-UP PATIENT LIST
					</div>
				</div>
				<div className="flex justify-between items-center gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
					<div className="mt-4 ml-4 text-sm font-semibold text-black max-md:max-w-full">
						Date Generated: {new Date().toLocaleDateString()}
						<br />
						Generated by: {currentUser.getState().user.first_name} {currentUser.getState().user.last_name}
					</div>
				</div>
				<div className="w-full flex justify-center items-center"></div>

				<div className="flex mt-4 w-full text-xs max-md:flex-wrap max-md:max-w-full">
					<Table>
						{/* To change to button */}
						<TableHeader>
							<TableRow>
								<TableHead className="w-[15%]">Patient Name</TableHead>
								<TableHead className="w-[20%]">Diagnosis</TableHead>
								<TableHead className="w-[10%]">Current Date</TableHead>
								<TableHead className="w-[15%]">Supposed Clinic Visit Date</TableHead>
								<TableHead className="w-[20%]">Last Clinic Visit Date</TableHead>
							</TableRow>
						</TableHeader>
						<TableBody>
							{patientInfo?.map((item, index) => (
								<TableRow key={index}>
									<TableCell className="font-medium">{item.name}</TableCell>
									<TableCell>{item.diagnosis}</TableCell>
									<TableCell>{item.currentDate}</TableCell>
									<TableCell className="text-left">{item.supposedClinicVisit}</TableCell>
									<TableCell className="text-left">{item.dateLastClinicVisit}</TableCell>
								</TableRow>
							))}
						</TableBody>
					</Table>
				</div>
				<div className="text-base text-sky-900 mt-8"></div>
			</div>
		</div>
	);
}
