"use client";
import * as React from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Link } from "next/link"; // Import Link component
import { currentUser } from "@/app/store";
import { toast } from "react-toastify";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export default function SelfprickList() {
  const router = useRouter(); // Initialize useRouter

  const patientInfo = [
    {
      name: "Juana Dela Cruz",
      selfprick: "143",
      when: "Before Eating",
      finding: "High",
    },
    {
      name: "Jollina Recto",
      selfprick: "90",
      when: "After Eating",
      finding: "Low",
    },
    {
      name: "Angel Borha",
      selfprick: "135",
      when: "Before Eating",
      finding: "High",
    },
    {
      name: "Fatima Reyes",
      selfprick: "170",
      when: "After Eating",
      finding: "High",
    },
  ];

  return (
    <div
      className="bg-white h-screen flex"
      style={{ overflowY: "scroll", maxHeight: "100vh" }}
    >
      <div className="flex flex-col grow shrink-0 self-start px-8 mt-14 basis-0 leading-[150%] w-fit max-md:mt-10 max-md:max-w-full">
        <div className="text-xl font-semibold text-black max-md:max-w-full">
          Reports
        </div>
        <div className="shrink-0 mt-5 h-px bg-black border border-black border-solid max-md:max-w-full" />
        <div className="flex justify-between gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-8 text-base font-semibold text-black max-md:max-w-full">
            LATE FOR FOLLOW-UP PATIENT LIST
          </div>

          <div className="mt-8 text-xs text-blue-500 max-md:max-w-full">
            <button>Download (.pdf)</button>
          </div>
        </div>
        <div className="flex justify-between items-center gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-4 ml-4 text-sm font-semibold text-black max-md:max-w-full">
            Date Generated: 2024-05-30
            <br />
            Generated by: Dr. John Doe
          </div>
        </div>
        <div className="w-full flex justify-center items-center"></div>

        <div className="flex mt-4 w-full text-xs max-md:flex-wrap max-md:max-w-full">
          <Table>
            {/* To change to button */}
            <TableHeader>
              <TableRow>
                <TableHead className="w-[15%]">Patient Name</TableHead>
                <TableHead className="w-[15%]">
                  Self Prick Sugar Value
                </TableHead>
                <TableHead className="w-[10%]">When</TableHead>
                <TableHead className="w-[15%]">Finding</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {patientInfo?.map((item, index) => (
                <TableRow key={index}>
                  <TableCell className="font-medium">{item.name}</TableCell>
                  <TableCell>{item.selfprick}</TableCell>
                  <TableCell>{item.when}</TableCell>
                  <TableCell className="text-left">{item.finding}</TableCell>
                  <TableCell>
                    <Button variant="outline">Message</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
        <div className="text-base text-xs text-sky-900 mt-8">
          <button className="flex items-center justify-center px-6 py-1 rounded text-xs border border-sky-900 border-solid font-semibold border-1.5">
            <div className="flex gap-0.5 justify-between items-center">
              <Image
                height={0}
                width={0}
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0de7471415fd70bdaba9dd1e6f7c2e7075e37988a454dfb91c7aed9b11350077?"
                className="w-3 h-3 aspect-square"
                alt="Back Arrow"
              />
              <div className="text-xs">BACK</div>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}
