import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import TopNav from "./topNav";
import Navbar from "./navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import React from "react";
import { LoadingProvider } from "./context/loadingContext";
import LoadingScreen from "./components/LoadingScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <LoadingProvider>
          <LoadingScreen />
          <ToastContainer />
          <Providers>
            <TopNav />
            <div className="flex">
              <Navbar />
              <div className="w-full">{children}</div>
            </div>
          </Providers>
        </LoadingProvider>
      </body>
    </html>
  );
}
