import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import TopNav from "./topNav";
import Navbar from "./navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="light">
			<body className={inter.className}>
				<ToastContainer />
				<Providers>
					<TopNav />
					<div className="flex">
						<Navbar />
						<div className="w-full">{children}</div>
					</div>
				</Providers>
			</body>
		</html>
	);
}
