"use client";
import * as React from "react";
import PieChart from "./pieChart";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Link } from "next/link"; // Import Link component
import { currentUser } from "@/app/store";
import { toast } from "react-toastify";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
export default function ReferredPatientList() {
  const router = useRouter(); // Initialize useRouter

  const patientInfo = [
    {
      name: "Marvin Raymundo",
      doctor: "Dr. Johnny Santos",
      specialization: "Cardiologist",

      datereferred: "April 20, 2024",
      status: "Accepted",
    },
    {
      name: "Marvin Raymundo",
      doctor: "Dr. Johnny Santos",
      specialization: "Cardiologist",
      datereferred: "April 20, 2024",
      status: "Accepted",
    },
    {
      name: "Marvin Raymundo",
      doctor: "Dr. Johnny Santos",
      specialization: "Cardiologist",
      datereferred: "April 20, 2024",
      status: "Accepted",
    },
    {
      name: "Marvin Raymundo",
      doctor: "Dr. Johnny Santos",
      specialization: "Cardiologist",
      datereferred: "April 20, 2024",

      status: "Accepted",
    },
  ];

  const practitioners = [
    { id: 1, name: "Dr. John Doe" },
    { id: 2, name: "Dr. Jane Smith" },
    { id: 3, name: "Dr. Mary Johnson" },
  ];
  const handlePractitionerChange = (event) => {
    const selectedPractitionerId = event.target.value;
    console.log(`Selected Practitioner ID: ${selectedPractitionerId}`);
  };

  return (
    <div
      className="bg-white h-screen flex"
      style={{ overflowY: "scroll", maxHeight: "100vh" }}
    >
      <div className="flex flex-col grow shrink-0 self-start px-8 mt-14 basis-0 leading-[150%] w-fit max-md:mt-10 max-md:max-w-full">
        <div className="text-xl font-semibold text-black max-md:max-w-full">
          Reports
        </div>
        <div className="shrink-0 mt-5 h-px bg-black border border-black border-solid max-md:max-w-full" />
        <div className="flex justify-between gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-8 text-base font-semibold text-black max-md:max-w-full">
            REFERRED PATIENTS LIST
          </div>

          <div className="mt-8 text-xs text-blue-500 max-md:max-w-full">
            <button>Download (.pdf)</button>
          </div>
        </div>
        <div className="flex justify-between items-center gap-5 px-5 w-full max-md:flex-wrap max-md:max-w-full">
          <div className="mt-4 ml-4 text-sm font-semibold text-black max-md:max-w-full">
            Date Generated: 2024-04-06
            <br />
            Generated by: Dr. John Doe
          </div>

          <button className="flex gap-1 text-sm py-1 px-2 whitespace-nowrap rounded-md border border-black border-solid">
            <Image
              loading="lazy"
              height={0}
              width={0}
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/80c3069d4b41f9638143beaab01442a1ee1faa03e69b5f02684db5e14364bb41?"
              className="aspect-square object-contain object-center w-4 overflow-hidden shrink-0 max-w-full"
            />
            <div>FILTER</div>
          </button>
        </div>

        <div className="flex flex-col">
          <div className="mt-4 w-[30%]">
            {/* Dropdown component */}
            <label
              htmlFor="practitionerSelect"
              className="block text-sm font-medium text-gray-700"
            >
              Practitioner
            </label>
            <select
              id="practitionerSelect"
              value=""
              onChange={handlePractitionerChange}
              className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
            >
              <option value="" disabled selected>
                Select a Practitioner
              </option>
              {practitioners.map((practitioner) => (
                <option key={practitioner.id} value={practitioner.id}>
                  {practitioner.name}
                </option>
              ))}
            </select>
          </div>
          <div className="flex-1">
            {/* PieChart component */}
            <PieChart></PieChart>
          </div>

          <div className="flex-1 mt-4 text-xs">
            {/* Table component */}
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[20%]">Patient Name</TableHead>
                  <TableHead>Doctor</TableHead>
                  <TableHead className="text-left">Specialization</TableHead>
                  <TableHead className="text-left">Date Referred</TableHead>
                  <TableHead className="text-left">Status</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {patientInfo.map((item, index) => (
                  <TableRow key={index}>
                    <TableCell className="font-medium">{item.name}</TableCell>
                    <TableCell>{item.doctor}</TableCell>
                    <TableCell>{item.specialization}</TableCell>
                    <TableCell className="text-left">
                      {item.datereferred}
                    </TableCell>
                    <TableCell className="text-left">{item.status}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>

        <div className="text-base text-xs text-sky-900 mt-8">
          <button className="flex items-center justify-center px-6 py-1 rounded text-xs border border-sky-900 border-solid font-semibold border-1.5">
            <div className="flex gap-0.5 justify-between items-center">
              <Image
                height={0}
                width={0}
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/0de7471415fd70bdaba9dd1e6f7c2e7075e37988a454dfb91c7aed9b11350077?"
                className="w-3 h-3 aspect-square"
                alt="Back Arrow"
              />
              <div className="text-xs">BACK</div>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}
